#!/bin/sh

#Detecing IPAddress of this machine
echo -e "\e[1;31m Detecing IP address of this machine. \e[0m"

IP=$(curl ipinfo.io/ip)

echo "$IP"

#installing requirements

echo -e "\e[1;31m Installing kubectl \e[0m"
sudo pacman --noconfirm -S kubectl -y

echo -e "\e[1;31m Installing kustomize \e[0m"
sudo pacman --noconfirm -S kustomize -y

echo -e "\e[1;31m Installing kubeseal \e[0m"
sudo pacman --noconfirm -S kubeseal -y

echo -e "\e[1;31m Installing Flux \e[0m"
sudo pacman --noconfirm -S flux-go -y

echo -e "\e[1;31m Installing hugo \e[0m"
sudo pacman --noconfirm -S hugo -y

echo -e "\e[1;31m Installing git \e[0m"
sudo pacman --noconfirm -S git -y

echo -e "\e[1;31m Installing jq yq  \e[0m"
sudo pacman --noconfirm -S jq yq -y

echo -e "\e[1;31m Installing OpenFaaS \e[0m"
curl -sSL https://cli.openfaas.com | sudo -E sh

echo -e "\e[1;31m Installing Docker and Docker-Compose \e[0m"
sudo pacman --noconfirm -S docker docker-compose -y

echo -e "\e[1;31m Installings Docker and Docker-COMpsoe \e[0m"
sudo pacman --noconfirm -S podman -y

echo -e "\e[1;31m Installing k3sup \e[0m"
sudo pacman -S k3sup
sudo install k3sup /usr/local/bin/

echo -e "\e[1;31m Installing npm for cdk8s \e[0m"
sudo pacman --noconfirm -S npm

echo -e "\e[1;31m Installing cdk8s \e[0m"
sudo npm install -g cdk8s-cli

echo -e "\e[1;31 Binding set enable-bracketed-patse on \e[0m"
echo -e "\e[1;31 THIS IS SET FOR THE CURRENT SHELL NOT FUTURE ENVIROMENTS \e[0m"
bind 'set enable-bracketed-paste on'

echo -e "\e[1;31 installing k3sup \e[0m"
curl -sLS https://get.k3sup.dev | sh
k3sup --help

echo -e "\e[1;31 Installing ufw firewall \e[0m"
sudo pacman --noconfirm -S ufw
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 6443/tcp
ufw allow 2222/tcp
ufw enable
systemctl enable --now ufw
ufw reload

echo -e "\e[1;31 setting k3sup variables. \e[0m"
export SSH_IP_ADDRESS="$IP"
export KUBE_CONFIG=${HOME}/.kube/config


#FLux creating a local git repo for flux
echo -e "\e[1;31 Setting variables for flux and git repo \e[0m"
FLUX_INFRA_DIR=${HOME}/git/flux-infra
CLUSTER="$IP"

#Making folders and git repo
mkdir -p ${FLUX_INFRA_DIR}/${CLUSTER} && \
git -C ${FLUX_INFRA_DIR} init && \
cd ${FLUX_INFRA_DIR}/${CLUSTER} && \
echo Cluster working directory: $(pwd)

#standing up k3sup instance
ssh-keygen -t rsa -b 4096
mkdir -p ${HOME}/.kube
k3sup install --ip ${IP} --local-path ${KUBE_CONFIG} \
	--k3s-extra-args '--disable traefik'
