#!/bin/sh

#installing requirements

echo -e "\e[1;31m Installing kubectl \e[0m"
sudo pacman -S kubectl -y

echo -e "\e[1;31m Installing kustomize \e[0m"
sudo pacman -S kustomize -y

echo -e "\e[1;31m Installing kubeseal \e[0m"
sudo pacman -S kubeseal -y

echo -e "\e[1;31m Installing Flux \e[0m"
sudo pacman -S flux-go -y

echo -e "\e[1;31m Installing hugo \e[0m"
sudo pacman -S hugo -y

echo -e "\e[1;31m Installing git \e[0m"
sudo pacman -S git -y

echo -e "\e[1;31m Installing jq yq  \e[0m"
sudo pacman -S jq yq -y

echo -e "\e[1;31m Installing OpenFaaS \e[0m"
curl -sSL https://cli.openfaas.com | sudo -E sh

echo -e "\e[1;31m Installing Docker and Docker-Compose \e[0m"
sudo pacman -S docker docker-compose -y

echo -e "\e[1;31m Installings Docker and Docker-COMpsoe \e[0m"
sudo pacman -S podman -y

echo -e "\e[1;31m Installing kubeseal \e[0m"
sudo pacman -S kubeseal-bin

echo -e "\e[1;31m Installing flux \e[0m"
sudo pacman -S flux-go

echo -e "\e[1;31m Installing k3sup \e[0m"
sudo pacman -S k3sup
sudo install k3sup /usr/local/bin/

echo -e "\e[1;31m Installing npm for cdk8s \e[0m"
sudo pacman -S npm

echo -e "\e[1;31m Installing cdk8s \e[0m"
sudo npm install -g cdk8s-cli

echo -e "\e[1;31 Binding set enable-bracketed-patse on \e[0m"
echo -e "\e[1;31 THIS IS SET FOR THE CURRENT SHELL NOT FUTURE ENVIROMENTS \e[0m"
bind 'set enable-bracketed-paste on'

#FLux creating a local git repo for flux
echo -e "\e[1;31 Setting variables for flux and git repo \e[0m"
FLUX_INFRA_DIR=${HOME}/git/flux-infra
CLUSTER=k3s.example.com

#Making folders and git repo
mkdir -p ${FLUX_INFRA_DIR}/${CLUSTER} && \
git -C ${FLUX_INFRA_DIR} init && \
cd ${FLUX_INFRA_DIR}/${CLUSTER} && \
echo Cluster working directory: $(pwd)



